config/routes.rb
Rails.application.routes.draw do

  get 'profile/show'
  get 'recipes/search'

  devise_for :users, :controllers => { registrations: 'registrations' }
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :categories

  scope ":user_name" do
    resources :recipes, as: 'user_recipes'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  root :to => 'home#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
   before_action :authenticate_user!
   before_action :set_user
   before_action :owned_profile, only: [:edit, :update]

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
        if @user.update(profile_params)
          format.html { redirect_to profile_path(@user.user_name), notice: "Your profile was updated successfully!" }
        else
          @user.errors.full_messages
          flash[:error] = @user.errors.full_messages
          render :edit
        end
      end
  end


  private

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class="container">
  <%= simple_form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
    <div class="row">
      <div class="col-md-12 col-sm-12">
         <div class="form-group text-center">
           <h4>Change your profile image:</h4>
             <div class="img-circle">
               <%= profile_avatar_select(@user) %>
             </div>
            <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
         </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1 col-md-10 offset-md-1 col-sm-12">
        <div class="form-group text-center">
          <h4>Update your bio:</h4>
          <%= f.input :bio, as: :bootsy, label: false, input_html: { rows: 5, cols: 80 }, placeholder: "Enter a Short Bio Here" %>
        </div>
      </div>
    </div>
    <div class="form-group text-center">
      <%= f.submit "Update Profile", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xl-6 offset-xl-3 col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-10 offset-sm-1 col-xs-10 offset-xs-1">
            <div class="card hovercard">
                <div class="cardheader">

                </div>
                <div class="avatar">
                  <%= profile_avatar_select(@user) %>
                </div>
                <div class="info">
                    <div class="title">
                        <%= @user.user_name %>
                    </div>
                    <div class="desc"><%= @user.first_name %> <%= @user.last_name %></div>
                    <div class="desc"><%= pluralize @user.recipes.count, 'recipe' %></div>
                </div>
                <div class="bottom">
                    <p class="profile-bio"><%= @user.bio.html_safe if @user.bio %></p>
                </div>

					</div>
        </div>

	</div>
  <div class="row">

    <div class="col-xl-6 offset-xl-3 col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-10 offset-sm-1 col-xs-10 offset-xs-1">
			<div class="d-flex justify-content-center">
      <% if @user == current_user %>
        <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn btn-primary' %>
      <% end %>
		  </div>
    </div>

  </div>
</div>