config/routes.rb
Rails.application.routes.draw do

  get 'profile/show'
  get 'recipes/search'

  devise_for :users, :controllers => { registrations: 'registrations' }
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :categories

  scope ":user_name" do
    resources :recipes, as: 'user_recipes'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  root :to => 'home#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :category, presence: true

  has_attached_file :image, styles: { medium: "500x350#", thumb: "300x200#"}, default_url: "default_image.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :user_id, presence: true

  def self.search params
    recipes = Recipe.where(category_id: params[:category].to_i) unless params[:category].blank?
    recipes
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_recipe, only: [:show, :edit, :update, :destroy]
  before_filter :prepare_categories

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = current_user.recipes.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
    @user = User.find_by(user_name: params[:user_name])
  end

  # GET /recipes/1/edit
  def edit
    @user = User.find_by(user_name: params[:user_name])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to user_recipe_path(current_user.user_name, @recipe), notice: "Your recipe was added successfully!" }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { redirect_to user_recipes_path, notice: "Your recipe could not be created. Please check the form and try again." }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to user_recipe_path(current_user.user_name, @recipe), notice: "Your recipe was updated successfully!" }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { redirect_to user_recipe_path(current_user.user_name, @recipe), notice: "Your recipe could not be updated. Please check the form and try again." }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
        format.html { render :edit }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to user_recipes_path(current_user.user_name), notice: "Your recipe was deleted successfully." }
      format.json { head :no_content }
    end
  end

  def search
    @filteredRecipes = Recipe.search(params)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:id, :title, :ingredients, :directions, :image, :user_name, :category_id)
    end

    def owned_recipe
      unless @recipe.user_id == current_user.id
        flash[:notice] = "That recipe doesn't exist."
        redirect_to user_recipes_path(current_user.user_name)
      end
    end

    def prepare_categories
      @categories = Category.all.order(name: :asc)
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_categorysearch.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <%= form_tag recipes_search_path, method: :get, role: 'form' do |f| %>
    <div class="recipe-search">
      <div class="form-group row form-inline">
      <%= select_tag 'category', options_for_select(Category.all.map{|el| [el.name, el.id]}), prompt: "Filter by Category:", class: 'form-control' %>
      <%= submit_tag 'Search', class: 'btn btn-primary' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/recipes/_form.html.erb
<div class="card" style="width: 44rem;">
    <div class="card-block">
      <h4 class="card-title">Recipe Entry</h4>
      <p class="card-text">
        <%= simple_form_for [:user, @recipe] do |form| %>
        <div class="form-group">
          <%= form.input :title, label: false, placeholder: "Recipe Title", input_html: { size: 81 }, class: "form-control" %></br>
          <%= form.collection_select(:category_id, @categories, :id, :name, include_blank: "Recipe Category") %></br></br>
          <%= form.input :ingredients, as: :bootsy, label: false, editor_options: { image: false }, input_html: { rows: 10, cols: 80 }, placeholder: "List Ingredients Here" %>
          <%= form.input :directions, as: :bootsy, label: false, editor_options: { image: false }, input_html: { rows: 10, cols: 80 }, placeholder: "List Directions Here" %>
          <%= form.input :image, as: :file, class: "form-control" %></br>
          <div class="row">
            <%= form.button :submit, class: "btn btn-primary" %>
            <%= link_to "Cancel", user_recipes_path , class: "btn" %>
          </div>
        </div>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/recipes/_recipenav.html.erb
<div class="container" id="sub-navigation">
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "My Recipes", user_recipes_path(current_user.user_name), class: "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to "New Recipe", new_user_recipe_path(current_user.user_name), class: "nav-link" %>
  </li>
</ul>
</div>

app/views/recipes/edit.html.erb
<%= render "recipenav", partial: true %>

<%= render 'form', recipe: @recipe %>

app/views/recipes/index.html.erb
<%= render "recipenav", partial: true %>

<div class="container-fluid">
  <div id="recipe" class="transitions-enabled centered clearfix masonry">
  <% if @recipes.count == 0  %>
    <div class="box col4">
      <div class="card-block">
        <h4 class="card-title">You have no recipes!</h4>
      </div>
    </div>
  <% else %>
    <% @recipes.each do |recipe| %>
      <div class="box col4">
        <%= link_to (image_tag recipe.image.url(:thumb)), user_recipe_path(current_user.user_name, recipe.id), class: "card-img-top" %>
          <div class="card-block">
            <h4 class="card-title"><%= recipe.title %></h4>
            <% if recipe.user_id == current_user.id %>
            <p class="card-text"><%= link_to 'Edit', edit_user_recipe_path(current_user.user_name, recipe.id) %> | <%= link_to 'Delete', user_recipe_path(current_user.user_name, recipe.id), method: :delete, data: { confirm: 'Are you sure?' } %></p>
            <% end %>
          </div>
        </div>
     <% end %>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<%= render "recipenav", partial: true %>

<%= render 'form', recipe: @recipe %>

app/views/recipes/search.html.erb
<%= render "recipenav", partial: true %>

<%= render "recipes/categorysearch", partial: true %>

<div class="container-fluid">
  <div id="recipe" class="transitions-enabled centered clearfix masonry">
  <% if @filteredRecipes.count == 0  %>
    <div class="box col4">
      <div class="card-block">
        <h4 class="card-title text-center">Your search returned no results!</h4>
      </div>
    </div>
  <% else %>
    <% @filteredRecipes.each do |recipe| %>
      <div class="box col4">
        <%= link_to (image_tag recipe.image.url(:thumb)), user_recipe_path(current_user.user_name, recipe.id), class: "card-img-top" %>
          <div class="card-block">
            <h4 class="card-title"><%= recipe.title %></h4>
            <% if recipe.user_id == current_user.id %>
            <p class="card-text"><%= link_to 'Edit', edit_user_recipe_path(current_user.user_name, recipe.id) %> | <%= link_to 'Delete', user_recipe_path(current_user.user_name, recipe.id), method: :delete, data: { confirm: 'Are you sure?' } %></p>
            <% end %>
          </div>
        </div>
     <% end %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<%= render "recipenav", partial: true %>

<div class="container" id="title-div">
  <div class="row">
    <div class="col text-center">
      <div class="recipe-image">
        <p><%= image_tag @recipe.image.url(:medium) %></p>
      </div>
    </div>
    <div class="col recipe-title text-center">
        <p><%= @recipe.title %></p>
    </div>
  </div>
</div>

<div class="container" id="ingredients-div">
  <div class="row">
    <div class="col text-center">
      <div class="ingredients-label">
        <span>Ingredients</span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="ingredients-text">
        <%= @recipe.ingredients.html_safe %>
      </div>
    </div>
  </div>
</div>


<div class="container" id="directions-div">
  <div class="row">
    <div class="col text-center">
      <div class="directions-label">
        <span>Directions</span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="directions-text">
        <%= @recipe.directions.html_safe %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="recipe-footer text-center">
        <% if @recipe.user_id == current_user.id %>
          <%= link_to 'Edit', edit_user_recipe_path(current_user.user_name, @recipe.id) %> |
        <% end %>
        <%= link_to 'Back', user_recipes_path %>
      </div>
    </div>
  </div>
</div>