config/routes.rb
Rails.application.routes.draw do

  get 'profile/show'
  get 'recipes/search'

  devise_for :users, :controllers => { registrations: 'registrations' }
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :categories

  scope ":user_name" do
    resources :recipes, as: 'user_recipes'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  root :to => 'home#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Your category was added successfully!" }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { redirect_to categories_path, notice: "Your recipe could not be created. Please check the form and try again." }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
         if @category.update(recipe_params)
            format.html { redirect_to @category, notice: 'Category was successfully updated.' }
            format.json { render :show, status: :ok, location: @category }
         else
            format.html { render :edit }
            format.json { render json: @category.errors, status: :unprocessable_entity }
         end
      end
  end

  def destroy
    @category.destroy
         respond_to do |format|
         format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
         format.json { head :no_content }
      end
  end

  private

  def set_recipe
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:id, :name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_catform.html.erb
<div class="card" style="width: 44rem;">
    <div class="card-block">
      <h4 class="card-title">New Category Entry</h4>
      <p class="card-text">
        <%= simple_form_for [@category] do |form| %>
        <div class="form-group">
          <%= form.input :name, label: false, placeholder: "Category Title", input_html: { size: 81 } %></br>
          <div class="row">
            <%= form.button :submit, class: "btn btn-primary" %>
            <%= link_to "Cancel", categories_path , class: "btn" %>
          </div>
        </div>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<%= link_to "New Category", new_category_path %>

<% @categories.each do |category| %>
  <h6><%= category.name %></h4>
<% end %>

app/views/categories/new.html.erb
<%= render 'catform', partial: true %>