config/routes.rb
Rails.application.routes.draw do

  get 'profile/show'
  get 'recipes/search'

  devise_for :users, :controllers => { registrations: 'registrations' }
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :categories

  scope ":user_name" do
    resources :recipes, as: 'user_recipes'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  root :to => 'home#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <div class="container">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if user_signed_in? %>
    <%= link_to (image_tag("RB.svg", :alt => "RecipeBox Logo", width: 40, height: 40, class: "logo")), user_recipes_path(current_user.user_name) %>
    <%= link_to "RecipeBox", user_recipes_path(current_user.user_name), class: "navbar-brand" %>
  <% else %>
    <%= link_to (image_tag("RB.svg", :alt => "RecipeBox Logo", width: 40, height: 40, class: "logo")), root_path %>
    <%= link_to "RecipeBox", root_path, class: "navbar-brand" %>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Profile", profile_path(current_user.user_name), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
      <span class="navbar-text">Welcome, <%= current_user.first_name %>!</span>
      <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
      <% end %>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBox</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= typekit 'gam7yrh' %>
  </head>

  <body data-turbolinks='false'>

    <%= render "layouts/navbar" %>

    <% if flash[:notice] %>
      <div class="container" id="alerts">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
              <% flash.each do |name, msg| %>
                <%= content_tag :div, msg %>
              <% end %>
        </div>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>